const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.NinePatch,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Text.Cnds.PickChildren,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.Text.Exps.Width,
		C3.Plugins.Text.Exps.Height
	];
};
self.C3_JsPropNameTable = [
	{avant_tile_background: 0},
	{apres_tile_background: 0},
	{Touch: 0},
	{separateur_sprite: 0},
	{Tween: 0},
	{POI_sprite: 0},
	{label_text: 0},
	{bgLabel_9patch: 0},
	{transition_input_zone_sprite: 0},
	{Icon: 0},
	{Browser: 0},
	{ref_poi_sprite: 0},
	{MAX_SWIPE: 0},
	{MIN_SWIPE: 0}
];

self.InstanceType = {
	avant_tile_background: class extends self.ITiledBackgroundInstance {},
	apres_tile_background: class extends self.ITiledBackgroundInstance {},
	Touch: class extends self.IInstance {},
	separateur_sprite: class extends self.ISpriteInstance {},
	POI_sprite: class extends self.ISpriteInstance {},
	label_text: class extends self.ITextInstance {},
	bgLabel_9patch: class extends self.IWorldInstance {},
	transition_input_zone_sprite: class extends self.ISpriteInstance {},
	Icon: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	ref_poi_sprite: class extends self.ISpriteInstance {}
}